        location = /3dpose { return 301 /3dpose/; }
        location = /3dpose/ { return 302 /3dpose/viewer.html; }
        location /3dpose/ {
            proxy_pass http://tennis_3dpose_viewer/;
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept-Encoding $http_accept_encoding;
            gzip on;
            gzip_types application/octet-stream application/json;
            gzip_proxied any;
        }
