server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index viewer.html;
    server_tokens off;
    charset utf-8;
    gzip_static on;
    gzip_vary on;
    gzip_proxied any;

    location = /healthz {
        default_type text/plain;
        return 200 'ok';
    }
    location / {
        try_files $uri =404;
        add_header Cache-Control 'public, max-age=300';
    }
    location ~* \.bin$ {
        try_files $uri =404;
        default_type application/octet-stream;
        add_header Cache-Control 'public, max-age=3600';
    }
    location = /video.mp4 {
        try_files $uri =404;
        add_header Cache-Control 'public, max-age=3600';
        add_header Accept-Ranges bytes;
    }
}
