// Draft calibration stays separate from the applied court transform.
(()=>{
const key='tennis-ground:30.56:1280x720:v3';for(const id of ['width','length']){$(id).readOnly=true;$(id).title='请在选点与微调窗口中修改尺寸';}
const panel=document.createElement('dialog');panel.id='groundEditor';panel.innerHTML=`<form method="dialog"><button class="close" aria-label="关闭地面标定">×</button></form><h2>地面四点标定</h2><p>在地面矩形上依次标记 A → B → C → D。点击角点可重新定位，方向键可微调 1 像素（Shift 为 10 像素）。</p><div class="row"><button id="draftUndo">撤销一步</button><button id="draftReset">重新选点</button><label>调整角点 <select id="draftPoint"><option value="0">A · 原点</option><option value="1">B · 宽方向</option><option value="2">C · 对角</option><option value="3">D · 长方向</option></select></label><label>AB 宽 / 米 <input id="draftWidth" type="number" min="0.1" step="0.01"></label><label>AD 长 / 米 <input id="draftLength" type="number" min="0.1" step="0.01"></label></div><canvas id="groundImage" tabindex="0" aria-label="地面标定选点画面"></canvas><p id="draftStatus" role="status" aria-live="polite"></p><div class="row"><button id="draftApply">应用并保存到本机</button><button id="draftCancel">取消修改</button></div><small>网格仅用于检查方向与地面线是否一致，不代表标定准确率。当前人体朝向仍使用估计相机参数。</small>`;document.body.appendChild(panel);
const style=document.createElement('style');style.textContent=`#groundEditor{width:min(1180px,96vw);max-height:94vh;overflow:auto;background:#152233;color:#e6eef8;border:1px solid #5b7491;border-radius:16px;padding:20px}#groundEditor::backdrop{background:#000b}#groundEditor h2{margin:0}#groundEditor .close{float:right}#groundImage{display:block;width:100%;height:auto;max-height:58vh;object-fit:contain;background:#0b111b;cursor:crosshair;outline:1px solid #51647a;touch-action:none}#groundImage:focus{outline:2px solid #6fcaff}#draftStatus{min-height:24px}#draftApply{background:#146859}#groundEditor input{width:100px}`;document.head.appendChild(style);
const canvas=$('groundImage'),g=canvas.getContext('2d');canvas.width=1280;canvas.height=720;
let draft=[],history=[],selected=0,frame=0,still=document.createElement('canvas');still.width=1280;still.height=720;
function snapshot(){history.push({points:structuredClone(draft),selected});}
function validate(){if(!data)throw Error('姿态数据尚未加载');if(draft.length!==4)throw Error(`已选 ${draft.length}/4 点：下一点为 ${'ABCD'[draft.length]}`);for(const p of draft)if(!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite)||p[0]<0||p[0]>1280||p[1]<0||p[1]>720)throw Error('角点必须在 1280 × 720 画面内');const area=Math.abs(draft.reduce((a,p,i)=>a+p[0]*draft[(i+1)%4][1]-p[1]*draft[(i+1)%4][0],0))/2;if(area<1000)throw Error('选取区域太小或接近共线，请扩大标定范围');const w=+$('draftWidth').value,l=+$('draftLength').value;if(!Number.isFinite(w)||!Number.isFinite(l)||w<.1||l<.1)throw Error('宽、长需要填写不小于 0.1 米的实测值');const result=calibrate(draft,w,l);result.frame=frame;result.image_size=[1280,720];result.video_id='30.56';result.version=2;return result;}
function draw(){g.clearRect(0,0,1280,720);g.drawImage(still,0,0);g.lineWidth=3;g.strokeStyle='#ffe079';g.fillStyle='#ffe07920';if(draft.length){g.beginPath();draft.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));if(draft.length===4)g.closePath();g.fill();g.stroke();}let result;try{result=validate();$('draftStatus').textContent=`几何检查通过 · ${result.width} × ${result.length} 米 · 第 ${frame+1} 帧 · 调整 ${'ABCD'[selected]}`;$('draftApply').disabled=false;const inv=homography([[0,0],[result.width,0],[result.width,result.length],[0,result.length]],draft);g.lineWidth=1;g.strokeStyle='#79e4de99';for(let i=1;i<10;i++){for(const pair of [[[result.width*i/10,0],[result.width*i/10,result.length]],[[0,result.length*i/10],[result.width,result.length*i/10]]]){g.beginPath();g.moveTo(...map(inv,pair[0]));g.lineTo(...map(inv,pair[1]));g.stroke()}}}catch(e){$('draftStatus').textContent=e.message;$('draftApply').disabled=true;}draft.forEach((p,i)=>{g.fillStyle=i===selected?'#65d9ff':'#ffe079';g.beginPath();g.arc(...p,9,0,Math.PI*2);g.fill();g.font='bold 22px system-ui';g.fillText(`${'ABCD'[i]} (${p.map(Math.round).join(', ')})`,p[0]>1050?p[0]-190:p[0]+14,Math.max(25,p[1]-14));});$('draftPoint').value=selected;$('draftUndo').disabled=!history.length;}
function open(){if(!data||v.readyState<2){$('calStatus').textContent='请等待视频与姿态数据加载完成';return;}v.pause();frame=n;still.getContext('2d').drawImage(v,0,0,1280,720);draft=structuredClone(cal?.points||[]);selected=0;history=[];$('draftWidth').value=cal?.width||$('width').value;$('draftLength').value=cal?.length||$('length').value;panel.showModal();draw();canvas.focus();}
function apply(result,persist=true){cal=result;points=structuredClone(result.points);picking=false;o.style.pointerEvents='none';$('width').value=result.width;$('length').value=result.length;$('space').querySelector('[value=calibrated]').disabled=false;$('space').value='calibrated';$('calStatus').textContent=`已应用 ${result.width} × ${result.length} 米标定 · 第 ${result.frame+1} 帧`;$('notice').textContent='实测地面映射已启用；人体尺度和朝向仍为单目估计。';if(persist)try{localStorage.setItem(key,JSON.stringify(result));$('calStatus').textContent+=' · 已保存到本机';}catch(e){$('calStatus').textContent+=' · 本机保存失败，请导出 JSON';}render();}
canvas.onclick=e=>{const r=canvas.getBoundingClientRect();const scale=Math.min(r.width/1280,r.height/720),left=r.left+(r.width-1280*scale)/2,top=r.top+(r.height-720*scale)/2;const p=[(e.clientX-left)/scale,(e.clientY-top)/scale];if(p[0]<0||p[0]>1280||p[1]<0||p[1]>720)return;snapshot();if(draft.length<4){draft.push(p);selected=Math.min(draft.length,3);}else{const near=draft.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<18/scale);if(near>=0)selected=near;else draft[selected]=p;}draw();canvas.focus();};
canvas.onkeydown=e=>{const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!moves[e.key]||!draft[selected])return;e.preventDefault();snapshot();draft[selected]=draft[selected].map((x,i)=>Math.max(0,Math.min(i?720:1280,x+moves[e.key][i]*(e.shiftKey?10:1))));draw();};
$('draftUndo').onclick=()=>{const old=history.pop();if(old){draft=old.points;selected=old.selected;draw();}};$('draftReset').onclick=()=>{snapshot();draft=[];selected=0;draw();};$('draftPoint').onchange=e=>{selected=+e.target.value;draw();canvas.focus();};for(const id of ['draftWidth','draftLength'])$(id).oninput=draw;$('draftCancel').onclick=()=>panel.close();$('draftApply').onclick=()=>{try{apply(validate());panel.close();}catch(e){$('draftStatus').textContent=e.message;}};
$('pick').textContent='打开选点与微调';$('pick').onclick=open;$('apply').textContent='检查 / 修改标定';$('apply').onclick=open;
const importButton=document.createElement('button');importButton.textContent='导入标定 JSON';$('export').after(importButton);const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.hidden=true;document.body.appendChild(file);importButton.onclick=()=>file.click();file.onchange=async()=>{try{const value=JSON.parse(await file.files[0].text());if(value.video_id&&value.video_id!=='30.56')throw Error('标定属于其他视频');if(value.image_size&&(value.image_size[0]!==1280||value.image_size[1]!==720))throw Error('标定分辨率不匹配');if(!Number.isInteger(value.frame)||value.frame<0||value.frame>=data.frames.length)throw Error('标定帧号无效');if(!Array.isArray(value.points)||value.points.length!==4||value.points.some(p=>!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite)))throw Error('需要四个有效角点');open();draft=value.points;frame=value.frame;$('draftWidth').value=value.width;$('draftLength').value=value.length;draw();$('draftStatus').textContent+=' · 导入草稿，请核对后应用';}catch(e){$('calStatus').textContent='导入失败：'+e.message;}finally{file.value='';}};
const oldClear=$('clear').onclick;$('clear').onclick=()=>{oldClear();try{localStorage.setItem(key,'null');}catch{}$('calStatus').textContent='已停用标定；可重新选点或导入 JSON';};
window.restoreGroundCalibration=()=>{try{const stored=localStorage.getItem(key);if(stored===null)return;if(stored==='null'){oldClear();return;}const value=JSON.parse(stored);draft=value.points;frame=value.frame;$('draftWidth').value=value.width;$('draftLength').value=value.length;if(!Number.isInteger(frame)||frame<0||frame>=data.frames.length)throw Error('保存的帧号无效');apply(validate(),false);}catch(e){$('calStatus').textContent='本机标定无效，已使用项目标定：'+e.message;}};
if(data)window.restoreGroundCalibration();
})();
